name: example
description: A Dart example program that can read and write numbers in the LEB128, short for Little Endian Base 128, format.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  leb128:
    path: ..

dev_dependencies:
  test: ^1.17.10
